@Pokedex_HostAddress = http://localhost:5272

GET {{Pokedex_HostAddress}}/api/pokemon/mewtwo
Accept: application/json

###

GET {{Pokedex_HostAddress}}/api/pokemon/translated/mewtwo
Accept: application/json
