name: CI

on:
  push:
    branches: [ "main" ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: src/*sln
      
      - name: Build
        run: dotnet build
        working-directory: src/*sln
      
      - name: Test with the dotnet CLI
        run: dotnet test
        working-directory: src/*sln
